from fpdf import FPDF
from datetime import datetime
import os

def generate_pdf(transcript, severity, explanation, output_path):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    # Title
    pdf.set_text_color(0, 0, 128)
    pdf.cell(200, 10, txt="MediMatch Emergency Report", ln=True, align='C')
    pdf.ln(10)

    # Info
    pdf.set_text_color(0, 0, 0)
    pdf.cell(200, 10, txt=f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
    pdf.cell(200, 10, txt=f"Severity Level: {severity.upper()}", ln=True)
    pdf.ln(10)

    # Transcript
    pdf.set_font("Arial", style="B", size=11)
    pdf.cell(200, 10, txt="Transcribed Symptoms:", ln=True)
    pdf.set_font("Arial", size=11)
    pdf.multi_cell(0, 10, txt=transcript)
    pdf.ln(5)

    # Explanation
    pdf.set_font("Arial", style="B", size=11)
    pdf.cell(200, 10, txt="AI Reasoning:", ln=True)
    pdf.set_font("Arial", size=11)
    pdf.multi_cell(0, 10, txt=explanation)

    # Footer
    pdf.ln(10)
    pdf.set_font("Arial", style="I", size=9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 10, txt="Generated by MediMatch AI Triage System", align='C')

    pdf.output(output_path)